### ISSUE TITLE
On Save with img pasted

### ISSUE THREAD

**Issue by MJacred** [founderio/emoticorg#14]
Requirements:
- pasted image

"+ New Emoticon" -> "Paste Image" -> optional: adding name or category -> "Save" -> error message with following stacktrace:

System.ArgumentNullException: Der Puffer darf nicht NULL sein.
Parametername: buffer
   bei System.IO.MemoryStream..ctor(Byte[] buffer, Boolean writable)
   bei System.IO.MemoryStream..ctor(Byte[] buffer)
   bei Emoticorg.MemoryImage.initWithData(Byte[] data)
   bei Emoticorg.EditForm.SetImageFromBytes(Byte[] buffer)
   bei Emoticorg.EditForm.Store()
   bei Emoticorg.EditForm.ShowInternal(Form parent)
   bei Emoticorg.EditForm.ShowNew(Form parent)
   bei Emoticorg.OrganizerForm.btnNewEmoticon_Click(Object sender, EventArgs e)
   bei System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   bei System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   bei System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   bei System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   bei System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   bei System.Windows.Forms.ToolStrip.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

![saving image](https://cloud.githubusercontent.com/assets/6639237/7916379/b6c5fd0e-0883-11e5-89c6-cbde6496ae4b.PNG)

![save img with empty fields](https://cloud.githubusercontent.com/assets/6639237/7916275/20613bf8-0883-11e5-875c-9007c2383bc9.PNG)

**Comment by founderio** [comment]
This looks like #7. Same reason. Now I think I have fixed it for good... Some Image Formats do not have encoders registered for writing out the image, e.g. MemoryBmp. Which makes sense, since it is pasted images that behave "stupid". In that case I just save as Png.
Before I just checked if there was a format - I did not check if it had an encoder..
